import Testing
import Foundation
@testable import ArtifactCore

@Suite("ArtifactParser (sync)")
struct ArtifactParserTests {

    @Test func emptySource() throws {
        let msg = try ArtifactParser.parse("")
        #expect(msg.segments.isEmpty)
    }

    @Test func plainTextOnly() throws {
        let msg = try ArtifactParser.parse("Hello, world.")
        #expect(msg.segments.count == 1)
        #expect(msg.plainText == "Hello, world.")
        #expect(msg.artifacts.isEmpty)
    }

    @Test func singleArtifact() throws {
        let source = #"""
        Prelude.
        <artifact identifier="a1" type="text/markdown" title="Note">
        # Hello
        </artifact>
        Coda.
        """#
        let msg = try ArtifactParser.parse(source)
        #expect(msg.artifacts.count == 1)
        let a = msg.artifacts[0]
        #expect(a.id.rawValue == "a1")
        #expect(a.type == .markdown)
        #expect(a.title == "Note")
        #expect(a.payload.contains("# Hello"))
        #expect(a.isComplete)
        #expect(msg.plainText.contains("Prelude."))
        #expect(msg.plainText.contains("Coda."))
    }

    @Test func multipleArtifacts() throws {
        let source = #"""
        <artifact identifier="a" type="text/html">one</artifact>
        between
        <artifact identifier="b" type="image/svg+xml">two</artifact>
        """#
        let msg = try ArtifactParser.parse(source)
        #expect(msg.artifacts.count == 2)
        #expect(msg.artifacts[0].type == .html)
        #expect(msg.artifacts[1].type == .svg)
        #expect(msg.plainText.contains("between"))
    }

    @Test func parseOneReturnsFirstArtifact() throws {
        let source = #"""
        <artifact identifier="x" type="text/markdown">body</artifact>
        """#
        let a = try ArtifactParser.parseOne(source)
        #expect(a.id.rawValue == "x")
        #expect(a.payload == "body")
    }

    @Test func parseOneThrowsWhenAbsent() {
        #expect(throws: ArtifactError.noArtifactFound) {
            try ArtifactParser.parseOne("just prose")
        }
    }

    @Test func unterminatedThrows() {
        let source = #"<artifact identifier="z" type="text/html">unfinished"#
        #expect(throws: ArtifactError.unterminatedArtifact(ArtifactIdentifier("z"))) {
            try ArtifactParser.parse(source)
        }
    }

    @Test func malformedOpenTagBecomesText() throws {
        // Missing required `type` attribute — treated as raw text.
        let source = #"<artifact identifier="x">body</artifact>"#
        let msg = try ArtifactParser.parse(source)
        #expect(msg.artifacts.isEmpty)
        #expect(msg.plainText.contains("<artifact"))
    }

    @Test func attributesAreCaptured() throws {
        let source = #"<artifact identifier="a" type="application/vnd.ant.code" language="swift" title="Demo">let x = 1</artifact>"#
        let a = try ArtifactParser.parseOne(source)
        #expect(a.attributes["language"] == "swift")
        #expect(a.title == "Demo")
        #expect(a.payload == "let x = 1")
    }

    @Test func xmlEntitiesInAttributeAreDecoded() throws {
        let source = #"<artifact identifier="a" type="text/html" title="A &amp; B">x</artifact>"#
        let a = try ArtifactParser.parseOne(source)
        #expect(a.title == "A & B")
    }

    @Test func identifierAutogeneratedWhenMissing() throws {
        let source = #"<artifact type="text/html">x</artifact>"#
        let a = try ArtifactParser.parseOne(source)
        #expect(!a.id.rawValue.isEmpty)
    }
}
